# Tensorflow bug29989
- Behaviour: Segmentation fault
- Description: Segmentation fault when saving checkpoints with saveable Dataset Iterator
- Affect version: 1.13.1
- Fixed version: tensroflow:latest